-- Luacheck configuration for Turtle Glasses Nvim.
-- Run locally / in CI: luacheck lua scripts --codes

-- Neovim plugin code runs inside the nvim process, so `vim` is an ambient
-- global rather than an import.
globals = { "vim" }

-- Scope the check to the plugin tree and its scripts. The generated palette
-- (lua/turtle-glasses/palette.lua, AUTO-GENERATED by
-- scripts/extract_palette.lua) is declared excluded here and additionally
-- scoped per-file below: luacheck applies `files` entries to command-line
-- files as per-file option overrides, so the exclude entry documents intent
-- while the per-file entry carries the actual rule.
files = {
  include = { "lua", "scripts" },
  exclude = { "lua/turtle-glasses/palette.lua" },
  ["lua/turtle-glasses/palette.lua"] = { ignore = { "631" } },
  -- is_array()'s empty-table loop returns on its first iteration on purpose
  -- (distinguish "no array items" from "non-empty hash part"), so W512
  -- ("loop is executed at most once") is noise for this file.
  ["scripts/extract_palette.lua"] = { ignore = { "512" } },
}

-- Wide rows are a deliberate style in this theme (single-line highlight
-- specs carrying fg/bg pairs and multi-family kind lists). The default
-- 120-column limit is too tight for them; raise it just past the longest
-- hand-written line (166) so genuinely overlong lines are still caught.
-- The generated palette's 400+ character value rows stay ignored per-file.
max_line_length = 170

-- Plugin modules expose a uniform `groups(palette, options)` signature so the
-- assembler (lua/turtle-glasses/theme.lua) calls them polymorphically; a few
-- plugins have no options to read, which is intentional and documented in
-- each module's doc comment.
ignore = { "212/options" }